deployment-nginx:
  name: nginx-deployment
  replicas: 1
  app: nginx
  image: nginx:latest
  containerPort: 80
  volumeMounts:
    - name: php-app-storage
      mountPath: /var/www/html
    - name: nginx-config-volume
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: default.conf
  volumes:
    - name: php-app-storage
      persistentVolumeClaim:
        claimName: php-app-pvc
    - name: nginx-config-volume
      configMap:
        name: nginx-config
        items:
          - key: default.conf
            path: default.conf

service-nginx:
  name: nginx-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000

persistent-volume:
  name: php-app-pv
  spec:
    capacity:
      storage: 10Mi
    accessModes:
      - ReadWriteMany
    hostPath:
      path: /mnt/data

persistent-volume-claim:
  name: php-app-pvc
  spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Mi