apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec:
  containers:
  - name: nginx
    # DockerHub image name
    image: nginx
  # - name: busybox
  #   image: busybox