apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: php-app-storage
          mountPath: /var/www/html
        - name: nginx-config-volume
          # mountPath: /etc/nginx/nginx.conf
          # subPath: nginx.conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: php-app-storage
        persistentVolumeClaim:
          claimName: php-app-pvc
      - name: nginx-config-volume
        configMap:
          name: nginx-config
          items:
            # - key: nginx.conf
            #   path: nginx.conf
            - key: default.conf
              path: default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
