---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx_deployment-release_name
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "2"
            memory: 4Gi
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
          - mountPath: /user/share/nginx/html
            name: nginx-index-file
      volumes:
        - name: nginx-index-file
          configMap:
            name: index-html-configmap
