apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ index .Values "persistent-volume" "name" }}
spec:
  {{ toYaml (index .Values "persistent-volume" "spec") | nindent 4 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ index .Values "persistent-volume-claim" "name" }}
spec:
  {{ toYaml (index .Values "persistent-volume-claim" "spec") | nindent 4 }}
